-- Generated by gen-orm | DB: mysql | 2026-05-16T17:23:26.686Z

CREATE TABLE IF NOT EXISTS streak_challenge_user_state (
  user_id VARCHAR(36) NOT NULL,
  event_id INT NOT NULL,
  cycle_id VARCHAR(36) NOT NULL,
  event_version INT NOT NULL,
  event_status VARCHAR(32) NOT NULL,
  activated_at DATETIME NOT NULL,
  expires_at DATETIME NOT NULL,
  current_level INT NOT NULL DEFAULT 0,
  last_counted_stage_id INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (user_id, event_id, cycle_id)
) COMMENT='One row per (user, event, cycle). Lazy Reset updates event_status on expiry.';
CREATE INDEX idx_streak_state_user_event ON streak_challenge_user_state (user_id, event_id);

CREATE TABLE IF NOT EXISTS streak_challenge_user_level_state (
  user_id VARCHAR(36) NOT NULL,
  event_id INT NOT NULL,
  cycle_id VARCHAR(36) NOT NULL,
  level_index INT NOT NULL,
  level_status VARCHAR(32) NOT NULL,
  required_count INT NOT NULL,
  current_count INT NOT NULL DEFAULT 0,
  started_at DATETIME,
  completed_at DATETIME,
  reward_state VARCHAR(32) NOT NULL DEFAULT 'NONE',
  reward_claimed_at DATETIME,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (user_id, event_id, cycle_id, level_index)
) COMMENT='Per-level progress for each user cycle. Reset only resets current_count, not completed levels.';
CREATE INDEX idx_streak_level_user_event ON streak_challenge_user_level_state (user_id, event_id, cycle_id);

CREATE TABLE IF NOT EXISTS streak_challenge_reward_claim_history (
  id BIGINT AUTO_INCREMENT NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  event_id INT NOT NULL,
  cycle_id VARCHAR(36) NOT NULL,
  level_index INT NOT NULL,
  reward_group_id INT NOT NULL,
  reward_group_version INT NOT NULL,
  reward_multiplier INT NOT NULL DEFAULT 1,
  claim_status VARCHAR(32) NOT NULL,
  correlation_id VARCHAR(36) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
) COMMENT='Append-only idempotency log for reward claims. correlation_id ensures duplicate-safe grants.';
CREATE INDEX idx_streak_claim_user_cycle ON streak_challenge_reward_claim_history (user_id, cycle_id, level_index);

CREATE TABLE IF NOT EXISTS streak_challenge_ad_reward_history (
  id BIGINT AUTO_INCREMENT NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  event_id INT NOT NULL,
  cycle_id VARCHAR(36) NOT NULL,
  level_index INT NOT NULL,
  ad_placement_id VARCHAR(64) NOT NULL,
  ad_result VARCHAR(32) NOT NULL,
  multiplier_applied TINYINT(1) NOT NULL DEFAULT false,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id)
) COMMENT='Append-only log of rewarded-ad attempts for streak challenge.';
CREATE INDEX idx_streak_ad_user_cycle ON streak_challenge_ad_reward_history (user_id, cycle_id, level_index);

-- Tables removed from schema (review before applying):
DROP TABLE IF EXISTS daily_challenge_progress;
