-- Generated by gen-orm | DB: mysql | 2026-05-12T11:34:48.538Z

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT AUTO_INCREMENT NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  session_id VARCHAR(36) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL,
  expires_at DATETIME NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT true,
  PRIMARY KEY (id)
);
CREATE INDEX idx_sessions_user_id ON sessions (user_id);

CREATE TABLE IF NOT EXISTS currency_logs (
  id BIGINT AUTO_INCREMENT NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  transaction_id VARCHAR(36) NOT NULL,
  currency_type VARCHAR(32) NOT NULL,
  delta BIGINT NOT NULL,
  balance_before BIGINT NOT NULL,
  balance_after BIGINT NOT NULL,
  reason TEXT NOT NULL,
  correlation_id VARCHAR(36) NOT NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id)
) COMMENT='Append-only audit log — never UPDATE or DELETE';
CREATE INDEX idx_currency_logs_user_id ON currency_logs (user_id);

CREATE TABLE IF NOT EXISTS daily_challenge_progress (
  user_id VARCHAR(36) NOT NULL,
  challenge_date DATE NOT NULL,
  play_count INT NOT NULL DEFAULT 0,
  completed TINYINT(1) NOT NULL DEFAULT false,
  streak_days INT NOT NULL DEFAULT 0,
  last_streak_date DATE,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (user_id, challenge_date)
) COMMENT='Per-user per-day challenge tracking — play count and streak state';
CREATE INDEX idx_daily_challenge_user_id ON daily_challenge_progress (user_id);

CREATE TABLE IF NOT EXISTS action_logs (
  id BIGINT AUTO_INCREMENT NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  action_type VARCHAR(64) NOT NULL,
  payload JSON,
  correlation_id VARCHAR(36) NOT NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id)
) COMMENT='Append-only general action audit log — never UPDATE or DELETE';
CREATE INDEX idx_action_logs_user_id ON action_logs (user_id);
CREATE INDEX idx_action_logs_action_type ON action_logs (action_type);
